spring:
  jpa:
    properties:
        hibernate:
          format_sql: true  # (3) SQL pretty print
    hibernate:
      ddl-auto: update  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: manager0
    url: jdbc:mysql://119.71.184.39:3306/jusedev?allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: dev
  sql:
    init:
      mode: always
#      schema-locations: classpath*:db/mysql/schema.sql
#      data-locations: classpath*:db/mysql/data.sql