spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 124440870106-l0gfn6q53m75am580s8noto6loh8pc4g.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: manager0
    url: jdbc:mysql://localhost:3306/juse?allowPublicKeyRetrieval=true&characterEncoding=UTF-8
  sql:
    init:
      mode: always
      data-locations: classpath*:db/mysql/data.sql