spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
    sqlScriptEncoding: UTF-8
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: H2
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 124440870106-l0gfn6q53m75am580s8noto6loh8pc4g.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile