spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 124440870106-l0gfn6q53m75am580s8noto6loh8pc4g.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile